/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminScannerRouteImport } from './routes/admin/scanner'
import { Route as AdminRiepilogoRouteImport } from './routes/admin/riepilogo'
import { Route as AdminPresenzeRouteImport } from './routes/admin/presenze'
import { Route as AdminImpostazioniRouteImport } from './routes/admin/impostazioni'
import { Route as AdminCreateRouteImport } from './routes/admin/create'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScannerRoute = AdminScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiepilogoRoute = AdminRiepilogoRouteImport.update({
  id: '/riepilogo',
  path: '/riepilogo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPresenzeRoute = AdminPresenzeRouteImport.update({
  id: '/presenze',
  path: '/presenze',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpostazioniRoute = AdminImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/setup': typeof SetupRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/impostazioni': typeof AdminImpostazioniRoute
  '/admin/presenze': typeof AdminPresenzeRoute
  '/admin/riepilogo': typeof AdminRiepilogoRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/setup': typeof SetupRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/impostazioni': typeof AdminImpostazioniRoute
  '/admin/presenze': typeof AdminPresenzeRoute
  '/admin/riepilogo': typeof AdminRiepilogoRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/setup': typeof SetupRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/impostazioni': typeof AdminImpostazioniRoute
  '/admin/presenze': typeof AdminPresenzeRoute
  '/admin/riepilogo': typeof AdminRiepilogoRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/profile'
    | '/setup'
    | '/admin/attendance'
    | '/admin/create'
    | '/admin/impostazioni'
    | '/admin/presenze'
    | '/admin/riepilogo'
    | '/admin/scanner'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/setup'
    | '/admin/attendance'
    | '/admin/create'
    | '/admin/impostazioni'
    | '/admin/presenze'
    | '/admin/riepilogo'
    | '/admin/scanner'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/profile'
    | '/setup'
    | '/admin/attendance'
    | '/admin/create'
    | '/admin/impostazioni'
    | '/admin/presenze'
    | '/admin/riepilogo'
    | '/admin/scanner'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scanner': {
      id: '/admin/scanner'
      path: '/scanner'
      fullPath: '/admin/scanner'
      preLoaderRoute: typeof AdminScannerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/riepilogo': {
      id: '/admin/riepilogo'
      path: '/riepilogo'
      fullPath: '/admin/riepilogo'
      preLoaderRoute: typeof AdminRiepilogoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/presenze': {
      id: '/admin/presenze'
      path: '/presenze'
      fullPath: '/admin/presenze'
      preLoaderRoute: typeof AdminPresenzeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impostazioni': {
      id: '/admin/impostazioni'
      path: '/impostazioni'
      fullPath: '/admin/impostazioni'
      preLoaderRoute: typeof AdminImpostazioniRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCreateRoute: typeof AdminCreateRoute
  AdminImpostazioniRoute: typeof AdminImpostazioniRoute
  AdminPresenzeRoute: typeof AdminPresenzeRoute
  AdminRiepilogoRoute: typeof AdminRiepilogoRoute
  AdminScannerRoute: typeof AdminScannerRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCreateRoute: AdminCreateRoute,
  AdminImpostazioniRoute: AdminImpostazioniRoute,
  AdminPresenzeRoute: AdminPresenzeRoute,
  AdminRiepilogoRoute: AdminRiepilogoRoute,
  AdminScannerRoute: AdminScannerRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
